[actually-all-emojis-spaces]
fetch.git = "https://github.com/jobiewong/espanso-emojis"
src.git = "https://github.com/jobiewong/espanso-emojis"

[lower-upper]
fetch.git = "https://github.com/anthonygraignic/espanso-package-lower-upper"
src.git = "https://github.com/anthonygraignic/espanso-package-lower-upper"

[mega-pack]
fetch.git = "https://github.com/jpmvferreira/espanso-mega-pack"
src.git = "https://github.com/jpmvferreira/espanso-mega-pack"

[ns]
fetch.url = "https://raw.githubusercontent.com/Vortriz/nix-search-tv/refs/heads/main/nixpkgs.sh"
src.manual = "latest"
url.name = "nixpkgs.sh"

[shyfox]
fetch.git = "https://github.com/Vortriz/ShyFox"
src.git = "https://github.com/Vortriz/ShyFox"

[starship-nerd-font-symbols]
fetch.url = "https://starship.rs/presets/toml/nerd-font-symbols.toml"
src.manual = "latest"
url.name = "nerd-font-symbols.toml"
